networks:
  ml-kit-network:
    driver: bridge

services:
  # -------------------------------------------------------
  # APPLICATION
  # -------------------------------------------------------
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - ml-kit-network

  # -------------------------------------------------------
  # NGINX
  # -------------------------------------------------------
  web:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ml-kit-network
